name: React CI/CD Pipeline

# Trigger the workflow on push or pull request events
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Set your desired Node version

      # Install dependencies
      - name: Install dependencies
        run: |
          npm install

      # Run tests (optional, if you have tests in your project)
      - name: Run tests
        run: |
          npx cypress run

      # Build the React app
      - name: Build app
        run: |
          npm run build

      # Optionally deploy the app (e.g., deploy to GitHub Pages or another service)
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build
